[project]
name = "gis-example"
version = "0.1.0"
description = "GIS example using Django and OpenLayers"
readme = "README.md"
requires-python = ">=3.14,<3.15"
dependencies = [
    "django>=6.0.5",
    "django-cors-headers>=4.9.0",
    "djangorestframework>=3.17.1",
    "python-dotenv>=1.2.2",
    "gdal>=3.10,<3.11",
    "djangorestframework-gis",
    "django-filter>=25.2",
    "drf-spectacular>=0.29.0",
    "djangorestframework-simplejwt>=5.5.1",
    "opentelemetry-distro>=0.62b1",
    "opentelemetry-instrumentation-asyncio==0.62b1",
    "opentelemetry-instrumentation-dbapi==0.62b1",
    "opentelemetry-instrumentation-logging==0.62b1",
    "opentelemetry-instrumentation-sqlite3==0.62b1",
    "opentelemetry-instrumentation-threading==0.62b1",
    "opentelemetry-instrumentation-urllib==0.62b1",
    "opentelemetry-instrumentation-wsgi==0.62b1",
    "opentelemetry-instrumentation-asgi==0.62b1",
    "opentelemetry-instrumentation-django==0.62b1",
    "gunicorn>=26.0.0",
    "whitenoise>=6.12.0",
]

[tool.uv]
index-url = "https://pypi.org/simple"

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "pytest-django>=4.12.0",
    "pytest-xdist>=3.8.0",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "gis_example.settings"
addopts = "-n auto"
