"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import tomllib
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


#
# Helper functions to read environment variables
#
def boolean(key: str, default=None) -> bool | None:
    """Convert an environment variable to a boolean."""
    if key in os.environ:
        value = os.environ[key].lower()
        if value in ("true", "1", "yes"):
            return True
        elif value in ("false", "0", "no"):
            return False
    return default


def required(key: str) -> str:
    """Get a required environment variable."""
    if key in os.environ:
        return os.environ[key]
    raise ImproperlyConfigured(f"Environment variable '{key}' is required")


def optional(key: str, default="") -> str:
    """Get an optional environment variable."""
    return os.environ.get(key, default)


def get_pyproject():
    pyproject = BASE_DIR / "pyproject.toml"
    with pyproject.open("rb") as f:
        pyproject_data = tomllib.load(f)
    return pyproject_data["project"]


# Load environment variables from .env file
load_dotenv()

# Load project metadata from pyproject.toml
PYPROJECT = get_pyproject()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

#
# Main settings
#

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = required("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = boolean("DEBUG", False)

ALLOWED_HOSTS = optional("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")

# CORS
CORS_ALLOW_ALL_ORIGINS = boolean("CORS_ALLOW_ALL_ORIGINS", True)
CORS_ALLOW_CREDENTIALS = boolean("CORS_ALLOW_CREDENTIALS", True)

# JWT settings
SIMPLE_JWT_ACCESS_TOKEN_LIFETIME = optional("SIMPLE_JWT_ACCESS_TOKEN_LIFETIME", "300")
SIMPLE_JWT_REFRESH_TOKEN_LIFETIME = optional(
    "SIMPLE_JWT_REFRESH_TOKEN_LIFETIME", "3600"
)

# OTEL settings
AUTO_INSRUMENT = boolean("AUTO_INSRUMENT", True)

#
# Whitenoise settings
#
USE_WHITENOISE_IN_DEV = boolean("USE_WHITENOISE_IN_DEV", True)
USE_WHITENOISE_STORAGE = boolean("USE_WHITENOISE_STORAGE", True)

#
# Django application configuration
#

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_filters",
    "corsheaders",
    "rest_framework",
    "rest_framework_gis",
    "drf_spectacular",
    "api",
]

if USE_WHITENOISE_IN_DEV:
    INSTALLED_APPS.insert(0, "whitenoise.runserver_nostatic")

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.spatialite",
        "NAME": optional("DB_NAME", "db.sqlite3"),
        "CONN_MAX_AGE": 300,
        "CONN_HEALTH_CHECKS": True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"

if USE_WHITENOISE_STORAGE:
    STORAGES = {
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        }
    }

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 100,
    "DEFAULT_FILTER_BACKENDS": ("django_filters.rest_framework.DjangoFilterBackend",),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
}

if boolean("REQUIRE_AUTHENTICATION", False):
    REST_FRAMEWORK["DEFAULT_PERMISSION_CLASSES"] = [
        "rest_framework.permissions.IsAuthenticated",
    ]

SPECTACULAR_SETTINGS = {
    "TITLE": PYPROJECT["name"],
    "DESCRIPTION": PYPROJECT.get("description", ""),
    "VERSION": PYPROJECT["version"],
    "SERVE_PUBLIC": True,
    "SERVE_INCLUDE_SCHEMA": True,
    "SERVE_PERMISSIONS": ["rest_framework.permissions.AllowAny"],
    # Other settings:
    "SCHEMA_COERCE_PATH_PK_SUFFIX": True,
    "SCHEMA_PATH_PREFIX": r"^/api/",
    "SWAGGER_UI_SETTINGS": {
        "docsExpansion": '["list", "full", "none"*]',
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(seconds=int(SIMPLE_JWT_ACCESS_TOKEN_LIFETIME)),
    "REFRESH_TOKEN_LIFETIME": timedelta(seconds=int(SIMPLE_JWT_REFRESH_TOKEN_LIFETIME)),
}
